### ISSUE TITLE
Unable to install collection from git due to missing version in galaxy.yml

### ISSUE THREAD

**Issue by dmsimard** [ansible-collections/openvswitch.openvswitch#59]
##### SUMMARY

According to the [documentation](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#installing-a-collection-from-a-git-repository) we should be able to install collections from git but for ``openvswitch.openvswitch``, it fails due to a lack of version in the galaxy.yml file.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
```

##### STEPS TO REPRODUCE
```yaml
ansible-galaxy collection install git+https://github.com/ansible-collections/openvswitch.openvswitch
```

##### EXPECTED RESULTS

Collection is installed successfully

##### ACTUAL RESULTS
```paste below
> ansible-galaxy collection install git+https://github.com/ansible-collections/openvswitch.openvswitch
Starting galaxy collection install process
Process install dependency map
ERROR! The collection galaxy.yml at '/home/dmsimard/.ansible/tmp/ansible-local-13386898nki5xno/tmphz_7siqo/openvswitch.openvswitch/galaxy.yml' is missing the following mandatory keys: version
```

**Comment by pabelanger** [comment]
So, I think for the we need to update ansible-galaxy CLI to handle it missing.  Or we expose something like

tox -ebuild

to generate a tarball to install from

**Comment by NilashishC** [comment]
> So, I think for the we need to update ansible-galaxy CLI to handle it missing. Or we expose something like
> 
> tox -ebuild
> 
> to generate a tarball to install from

@pabelanger Agreed. This ideally needs to be fixed in ansible-galaxy. This PR is just a workaround until that happens.
