### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains sanity/ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/openvswitch.openvswitch#72]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If everything is OK, feel free to close the issue

**Comment by NilashishC** [comment]
Hi @Andersson007. This collection is being tested with 2.11. Please refer to the jobs in https://dashboard.zuul.ansible.com/t/ansible/builds?project=ansible-collections%2Fopenvswitch.openvswitch#.

Closing as per above.

**Comment by Andersson007** [comment]
Hi @NilashishC cool, thanks
